# Generated by Django 5.2.8 on 2025-12-02 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_customer_ssh_host_key_policy"),
        ("jobs", "0004_git_integration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "team_id",
                    models.CharField(help_text="Slack team ID", max_length=100, unique=True),
                ),
                ("team_name", models.CharField(help_text="Slack team name", max_length=255)),
                (
                    "bot_token",
                    models.CharField(help_text="Slack bot OAuth token (encrypted)", max_length=255),
                ),
                ("bot_user_id", models.CharField(help_text="Slack bot user ID", max_length=100)),
                (
                    "signing_secret",
                    models.CharField(
                        help_text="Slack signing secret for request verification", max_length=255
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_workspaces",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlackUserMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slack_user_id", models.CharField(help_text="Slack user ID", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_mappings",
                        to="chatops.slackworkspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlackChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("channel_id", models.CharField(help_text="Slack channel ID", max_length=100)),
                ("channel_name", models.CharField(help_text="Slack channel name", max_length=255)),
                ("notify_job_completion", models.BooleanField(default=False)),
                ("notify_job_failure", models.BooleanField(default=True)),
                ("notify_compliance_violations", models.BooleanField(default=False)),
                ("notify_drift_detected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="chatops.slackworkspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatOpsCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slack_user_id", models.CharField(help_text="Slack user ID", max_length=100)),
                (
                    "channel_id",
                    models.CharField(help_text="Channel where command was issued", max_length=100),
                ),
                ("command", models.CharField(help_text="Command text", max_length=255)),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("unauthorized", "Unauthorized"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_text", models.TextField(blank=True, help_text="Response sent to user")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated job if command created one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chatops_commands",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatops_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="chatops.slackworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="slackworkspace",
            index=models.Index(fields=["customer"], name="chatops_sla_custome_2c8015_idx"),
        ),
        migrations.AddIndex(
            model_name="slackworkspace",
            index=models.Index(fields=["team_id"], name="chatops_sla_team_id_cc889d_idx"),
        ),
        migrations.AddIndex(
            model_name="slackusermapping",
            index=models.Index(fields=["workspace"], name="chatops_sla_workspa_45024b_idx"),
        ),
        migrations.AddIndex(
            model_name="slackusermapping",
            index=models.Index(fields=["slack_user_id"], name="chatops_sla_slack_u_53e99d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="slackusermapping",
            unique_together={("workspace", "slack_user_id")},
        ),
        migrations.AddIndex(
            model_name="slackchannel",
            index=models.Index(fields=["workspace"], name="chatops_sla_workspa_961f87_idx"),
        ),
        migrations.AddIndex(
            model_name="slackchannel",
            index=models.Index(fields=["channel_id"], name="chatops_sla_channel_5e1379_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="slackchannel",
            unique_together={("workspace", "channel_id")},
        ),
        migrations.AddIndex(
            model_name="chatopscommand",
            index=models.Index(fields=["workspace"], name="chatops_cha_workspa_c62aee_idx"),
        ),
        migrations.AddIndex(
            model_name="chatopscommand",
            index=models.Index(fields=["user"], name="chatops_cha_user_id_217622_idx"),
        ),
        migrations.AddIndex(
            model_name="chatopscommand",
            index=models.Index(fields=["created_at"], name="chatops_cha_created_984e72_idx"),
        ),
    ]
