# Generated by Django 5.2.8 on 2025-12-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="ssh_host_key_policy",
            field=models.CharField(
                choices=[
                    ("strict", "Strict - Reject unknown/changed keys"),
                    ("tofu", "TOFU - Accept first, warn on change"),
                    ("disabled", "Disabled - No verification (not recommended)"),
                ],
                default="tofu",
                help_text="SSH host key verification policy for this customer",
                max_length=20,
            ),
        ),
    ]
