# Generated by Django 5.2.8 on 2025-11-27 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("_password", models.TextField(db_column="password")),
                (
                    "_enable_password",
                    models.TextField(blank=True, db_column="enable_password", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("customer", "name")},
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hostname", models.CharField(max_length=255)),
                ("mgmt_ip", models.CharField(max_length=45)),
                ("vendor", models.CharField(max_length=50)),
                ("platform", models.CharField(max_length=50)),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("site", models.CharField(blank=True, max_length=100, null=True)),
                ("tags", models.JSONField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("reachability_status", models.CharField(blank=True, max_length=20, null=True)),
                ("last_reachability_check", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="devices.credential",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["hostname"],
            },
        ),
        migrations.CreateModel(
            name="TopologyLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("local_interface", models.CharField(max_length=100)),
                ("remote_hostname", models.CharField(max_length=255)),
                ("remote_interface", models.CharField(max_length=100)),
                ("remote_ip", models.CharField(blank=True, max_length=45, null=True)),
                ("remote_platform", models.CharField(blank=True, max_length=100, null=True)),
                ("protocol", models.CharField(default="lldp", max_length=10)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("job_id", models.IntegerField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="customers.customer"
                    ),
                ),
                (
                    "local_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="devices.device",
                    ),
                ),
                (
                    "remote_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_links",
                        to="devices.device",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["role"], name="devices_dev_role_df5c1a_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["site"], name="devices_dev_site_fb0a0c_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["vendor"], name="devices_dev_vendor_1d54db_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("customer", "hostname")},
        ),
        migrations.AddIndex(
            model_name="topologylink",
            index=models.Index(fields=["local_device"], name="devices_top_local_d_8bc037_idx"),
        ),
        migrations.AddIndex(
            model_name="topologylink",
            index=models.Index(fields=["remote_device"], name="devices_top_remote__d806e3_idx"),
        ),
        migrations.AddIndex(
            model_name="topologylink",
            index=models.Index(fields=["customer"], name="devices_top_custome_3f4924_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="topologylink",
            unique_together={
                (
                    "customer",
                    "local_device",
                    "local_interface",
                    "remote_hostname",
                    "remote_interface",
                )
            },
        ),
    ]
