# Generated by Django 5.2.8 on 2025-12-01 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveredDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hostname", models.CharField(max_length=255)),
                ("mgmt_ip", models.CharField(blank=True, max_length=45, null=True)),
                ("platform", models.CharField(blank=True, max_length=100, null=True)),
                ("vendor", models.CharField(blank=True, max_length=50, null=True)),
                ("discovered_via_protocol", models.CharField(default="lldp", max_length=10)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("job_id", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("ignored", "Ignored"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_source",
                        to="devices.device",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovered_devices",
                        to="customers.customer",
                    ),
                ),
                (
                    "discovered_via_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovered_neighbors",
                        to="devices.device",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_discoveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-discovered_at"],
                "indexes": [
                    models.Index(fields=["status"], name="devices_dis_status_ebfddc_idx"),
                    models.Index(fields=["customer"], name="devices_dis_custome_995fc9_idx"),
                    models.Index(fields=["discovered_at"], name="devices_dis_discove_fef98a_idx"),
                ],
                "unique_together": {("customer", "hostname")},
            },
        ),
    ]
