# Generated by Django 5.2.8 on 2025-12-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_add_discovered_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="discovery_protocol",
            field=models.CharField(
                choices=[("cdp", "CDP only"), ("lldp", "LLDP only"), ("both", "Both CDP and LLDP")],
                default="both",
                max_length=10,
            ),
        ),
    ]
