# Generated by Django 5.2.8 on 2025-12-01 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("devices", "0003_add_device_discovery_protocol"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetBoxConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="NetBox",
                        help_text="Friendly name for this NetBox instance",
                        max_length=100,
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        help_text="NetBox API URL (e.g., https://netbox.example.com/api)",
                        max_length=500,
                    ),
                ),
                (
                    "_api_token",
                    models.TextField(db_column="api_token", help_text="Encrypted NetBox API token"),
                ),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Only"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="manual",
                        help_text="How often to sync from NetBox",
                        max_length=20,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Whether automatic sync is enabled"
                    ),
                ),
                (
                    "site_filter",
                    models.CharField(
                        blank=True,
                        help_text="Only sync devices from these NetBox sites (comma-separated slugs)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tenant_filter",
                    models.CharField(
                        blank=True,
                        help_text="Only sync devices from these NetBox tenants (comma-separated slugs)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "role_filter",
                    models.CharField(
                        blank=True,
                        help_text="Only sync devices with these roles (comma-separated slugs)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status_filter",
                    models.CharField(
                        blank=True,
                        default="active",
                        help_text="Device status filter (e.g., 'active', 'staged')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "field_mappings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom field mappings from NetBox to webnet (JSON)",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, help_text="Last successful sync timestamp", null=True
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        help_text="Status of last sync attempt (success, failed, partial)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "last_sync_message",
                    models.TextField(
                        blank=True, help_text="Message or error from last sync attempt", null=True
                    ),
                ),
                (
                    "last_sync_stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stats from last sync (created, updated, skipped counts)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        help_text="Customer this NetBox configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="netbox_config",
                        to="customers.customer",
                    ),
                ),
                (
                    "default_credential",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default credential to assign to synced devices",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="netbox_configs",
                        to="devices.credential",
                    ),
                ),
            ],
            options={
                "verbose_name": "NetBox Configuration",
                "verbose_name_plural": "NetBox Configurations",
            },
        ),
        migrations.CreateModel(
            name="NetBoxSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("devices_created", models.IntegerField(default=0)),
                ("devices_updated", models.IntegerField(default=0)),
                ("devices_skipped", models.IntegerField(default=0)),
                ("devices_failed", models.IntegerField(default=0)),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Summary message or error details", null=True
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Detailed sync results per device"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="devices.netboxconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["config"], name="devices_net_config__8c9e29_idx"),
                    models.Index(fields=["status"], name="devices_net_status_d445b4_idx"),
                    models.Index(fields=["started_at"], name="devices_net_started_e93209_idx"),
                ],
            },
        ),
    ]
