# Generated by Django 5.2.8 on 2025-12-01 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("devices", "0003_add_device_discovery_protocol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("static", "Static (explicit device list)"),
                            ("dynamic", "Dynamic (filter-based)"),
                        ],
                        default="static",
                        max_length=10,
                    ),
                ),
                ("filter_rules", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", help_text="Hex color code (e.g., #3B82F6)", max_length=7
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Optional tag category for grouping",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="discovereddevice",
            name="credential_test_status",
            field=models.CharField(
                blank=True,
                help_text="Result of credential testing: success, failed, untested",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discovereddevice",
            name="credential_tested",
            field=models.ForeignKey(
                blank=True,
                help_text="Last credential successfully tested",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tested_discoveries",
                to="devices.credential",
            ),
        ),
        migrations.AddField(
            model_name="discovereddevice",
            name="discovery_source",
            field=models.CharField(
                choices=[
                    ("topology", "CDP/LLDP Topology Discovery"),
                    ("ip_scan", "IP Range Scan"),
                    ("snmp", "SNMP Discovery"),
                    ("manual", "Manual Entry"),
                ],
                default="topology",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="discovereddevice",
            name="interfaces_json",
            field=models.JSONField(
                blank=True, help_text="Discovered interfaces as JSON list", null=True
            ),
        ),
        migrations.AddField(
            model_name="discovereddevice",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="discovereddevice",
            name="software_version",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="discovereddevice",
            index=models.Index(fields=["discovery_source"], name="devices_dis_discove_d60953_idx"),
        ),
        migrations.AddIndex(
            model_name="discovereddevice",
            index=models.Index(fields=["mgmt_ip"], name="devices_dis_mgmt_ip_0a9196_idx"),
        ),
        migrations.AddField(
            model_name="devicegroup",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_groups",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="devicegroup",
            name="devices",
            field=models.ManyToManyField(
                blank=True, related_name="static_groups", to="devices.device"
            ),
        ),
        migrations.AddField(
            model_name="devicegroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="devices.devicegroup",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="device_tags",
            field=models.ManyToManyField(blank=True, related_name="devices", to="devices.tag"),
        ),
        migrations.AddIndex(
            model_name="devicegroup",
            index=models.Index(fields=["customer"], name="devices_dev_custome_9cedcb_idx"),
        ),
        migrations.AddIndex(
            model_name="devicegroup",
            index=models.Index(fields=["group_type"], name="devices_dev_group_t_eeef8f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="devicegroup",
            unique_together={("customer", "name")},
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["customer"], name="devices_tag_custome_fad117_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["category"], name="devices_tag_categor_32b825_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("customer", "name")},
        ),
    ]
