# Generated by Django 5.2.8 on 2025-12-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_add_tags_groups_bulk_discovery'),
        ('devices', '0004_netbox_integration'),
    ]

    operations = [
    ]
