# Generated by Django 5.2.8 on 2025-12-01 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_merge_20251201_2108"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="netboxconfig",
            name="_api_token",
            field=models.TextField(
                db_column="api_token", help_text="Encrypted NetBox API token (required)"
            ),
        ),
        migrations.CreateModel(
            name="SSHHostKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("ssh-rsa", "RSA"),
                            ("ecdsa-sha2-nistp256", "ECDSA P-256"),
                            ("ecdsa-sha2-nistp384", "ECDSA P-384"),
                            ("ecdsa-sha2-nistp521", "ECDSA P-521"),
                            ("ssh-ed25519", "Ed25519"),
                        ],
                        help_text="SSH key algorithm type",
                        max_length=30,
                    ),
                ),
                ("public_key", models.TextField(help_text="Base64-encoded public key data")),
                (
                    "fingerprint_sha256",
                    models.CharField(
                        help_text="SHA256 fingerprint of the public key", max_length=64
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this key was first seen"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(auto_now=True, help_text="When this key was last seen"),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this key has been manually verified by an operator",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When this key was verified", null=True
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Device this host key belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssh_host_keys",
                        to="devices.device",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who verified this key",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_host_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-verified", "-first_seen_at"],
                "indexes": [
                    models.Index(fields=["device"], name="devices_ssh_device__57758c_idx"),
                    models.Index(
                        fields=["fingerprint_sha256"], name="devices_ssh_fingerp_202533_idx"
                    ),
                    models.Index(fields=["verified"], name="devices_ssh_verifie_d65d1d_idx"),
                ],
                "unique_together": {("device", "key_type", "fingerprint_sha256")},
            },
        ),
    ]
