# Generated by Django 5.2.8 on 2025-12-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_merge_20251201_2108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="netboxconfig",
            name="_api_token",
            field=models.TextField(
                db_column="api_token", help_text="Encrypted NetBox API token (required)"
            ),
        ),
    ]
