# Generated by Django 5.2.8 on 2025-12-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_netboxconfig__api_token'),
        ('devices', '0006_alter_netboxconfig__api_token_sshhostkey'),
    ]

    operations = [
    ]
