# Generated by Django 5.2.8 on 2025-12-02 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_ssh_host_key_policy'),
        ('devices', '0007_merge_20251202_0016'),
        ('jobs', '0004_git_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ServiceNow', help_text='Friendly name for this ServiceNow instance', max_length=100)),
                ('instance_url', models.URLField(help_text='ServiceNow instance URL (e.g., https://yourinstance.service-now.com)', max_length=500)),
                ('username', models.CharField(help_text='ServiceNow username for API access', max_length=100)),
                ('_password', models.TextField(db_column='password', help_text='Encrypted ServiceNow password (required)')),
                ('cmdb_table', models.CharField(default='cmdb_ci_netgear', help_text='ServiceNow CMDB table name (e.g., cmdb_ci_netgear, cmdb_ci_network_equipment)', max_length=100)),
                ('ci_class', models.CharField(blank=True, help_text='CI class filter (e.g., cmdb_ci_netgear)', max_length=100, null=True)),
                ('ci_query_filter', models.CharField(blank=True, help_text='Additional ServiceNow query filter (e.g., operational_status=1)', max_length=500, null=True)),
                ('company_sys_id', models.CharField(blank=True, help_text='Company sys_id to associate with CIs', max_length=32, null=True)),
                ('device_to_cmdb_mappings', models.JSONField(blank=True, default=dict, help_text='Custom field mappings from webnet Device to ServiceNow CI (JSON)')),
                ('cmdb_to_device_mappings', models.JSONField(blank=True, default=dict, help_text='Custom field mappings from ServiceNow CI to webnet Device (JSON)')),
                ('sync_frequency', models.CharField(choices=[('manual', 'Manual Only'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='manual', help_text='How often to sync with ServiceNow', max_length=20)),
                ('bidirectional_sync', models.BooleanField(default=True, help_text='Enable bi-directional sync (both import and export)')),
                ('auto_sync_enabled', models.BooleanField(default=False, help_text='Whether automatic sync is enabled')),
                ('create_incidents_on_failure', models.BooleanField(default=False, help_text='Automatically create incidents when jobs fail')),
                ('incident_category', models.CharField(blank=True, help_text='Default incident category', max_length=100, null=True)),
                ('incident_assignment_group', models.CharField(blank=True, help_text='Default incident assignment group sys_id', max_length=32, null=True)),
                ('create_changes_on_deploy', models.BooleanField(default=False, help_text='Automatically create change requests for config deployments')),
                ('change_category', models.CharField(blank=True, help_text='Default change request category', max_length=100, null=True)),
                ('change_assignment_group', models.CharField(blank=True, help_text='Default change assignment group sys_id', max_length=32, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('last_sync_status', models.CharField(blank=True, help_text='Status of last sync attempt (success, failed, partial)', max_length=20, null=True)),
                ('last_sync_message', models.TextField(blank=True, help_text='Message or error from last sync attempt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(help_text='Customer this ServiceNow configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='servicenow_config', to='customers.customer')),
                ('default_credential', models.ForeignKey(blank=True, help_text='Default credential to assign to imported devices', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicenow_configs', to='devices.credential')),
            ],
            options={
                'verbose_name': 'ServiceNow Configuration',
                'verbose_name_plural': 'ServiceNow Configurations',
            },
        ),
        migrations.CreateModel(
            name='ServiceNowChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_number', models.CharField(help_text='ServiceNow change request number (e.g., CHG0012345)', max_length=50)),
                ('change_sys_id', models.CharField(help_text='ServiceNow change request sys_id', max_length=32)),
                ('state', models.IntegerField(choices=[(-5, 'New'), (0, 'Assess'), (1, 'Authorize'), (2, 'Scheduled'), (3, 'Implement'), (4, 'Review'), (6, 'Closed')], default=-5)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('justification', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(help_text='Job associated with this change request', on_delete=django.db.models.deletion.CASCADE, related_name='servicenow_change_requests', to='jobs.job')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='devices.servicenowconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['config'], name='devices_ser_config__19e8e4_idx'), models.Index(fields=['job'], name='devices_ser_job_id_75c46a_idx'), models.Index(fields=['change_number'], name='devices_ser_change__88a490_idx'), models.Index(fields=['state'], name='devices_ser_state_9fc598_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceNowIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(help_text='ServiceNow incident number (e.g., INC0012345)', max_length=50)),
                ('incident_sys_id', models.CharField(help_text='ServiceNow incident sys_id', max_length=32)),
                ('state', models.IntegerField(choices=[(1, 'New'), (2, 'In Progress'), (3, 'On Hold'), (6, 'Resolved'), (7, 'Closed')], default=1)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='devices.servicenowconfig')),
                ('job', models.ForeignKey(help_text='Job that triggered this incident', on_delete=django.db.models.deletion.CASCADE, related_name='servicenow_incidents', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['config'], name='devices_ser_config__574f65_idx'), models.Index(fields=['job'], name='devices_ser_job_id_0c5360_idx'), models.Index(fields=['incident_number'], name='devices_ser_inciden_7f4d53_idx'), models.Index(fields=['state'], name='devices_ser_state_567e51_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceNowSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('import', 'Import from ServiceNow'), ('export', 'Export to ServiceNow')], default='export', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('devices_created', models.IntegerField(default=0)),
                ('devices_updated', models.IntegerField(default=0)),
                ('devices_skipped', models.IntegerField(default=0)),
                ('devices_failed', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, help_text='Summary message or error details', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed sync results per device')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='devices.servicenowconfig')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['config'], name='devices_ser_config__d46d39_idx'), models.Index(fields=['status'], name='devices_ser_status_a2e743_idx'), models.Index(fields=['started_at'], name='devices_ser_started_c8765f_idx')],
            },
        ),
    ]
