# Generated by Django 5.2.8 on 2025-12-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0007_merge_20251202_0016"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="custom_fields",
            field=models.JSONField(
                blank=True, default=dict, help_text="Custom field values stored as JSON"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="custom_fields",
            field=models.JSONField(
                blank=True, default=dict, help_text="Custom field values stored as JSON"
            ),
        ),
        migrations.AddField(
            model_name="devicegroup",
            name="custom_fields",
            field=models.JSONField(
                blank=True, default=dict, help_text="Custom field values stored as JSON"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="custom_fields",
            field=models.JSONField(
                blank=True, default=dict, help_text="Custom field values stored as JSON"
            ),
        ),
    ]
