# Generated by Django 5.2.8 on 2025-12-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0008_add_custom_fields"),
        ("devices", "0008_add_region_to_device"),
        ("devices", "0008_servicenow_integration"),
    ]

    operations = []
