# Generated by Django 5.2.8 on 2025-12-01

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0009_merge_20251202_1458"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="site_address",
            field=models.CharField(
                blank=True,
                help_text="Human-readable location/address for the site",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="site_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude for the device's site (degrees)",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="site_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude for the device's site (degrees)",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ],
            ),
        ),
    ]
