# Generated by Django 5.2.8 on 2025-12-02 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_customer_ssh_host_key_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Friendly name for this webhook", max_length=100),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Destination URL for webhook POST requests", max_length=500
                    ),
                ),
                (
                    "event_types",
                    models.JSONField(
                        default=list, help_text="List of event types this webhook subscribes to"
                    ),
                ),
                (
                    "_secret",
                    models.TextField(
                        blank=True,
                        db_column="secret",
                        help_text="Encrypted secret token for HMAC signature verification",
                        null=True,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, help_text="Whether this webhook is active"),
                ),
                (
                    "verify_ssl",
                    models.BooleanField(
                        default=True, help_text="Whether to verify SSL certificates for HTTPS URLs"
                    ),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(default=10, help_text="Request timeout in seconds"),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum number of retry attempts for failed deliveries",
                    ),
                ),
                (
                    "retry_backoff",
                    models.IntegerField(
                        default=60,
                        help_text="Initial retry backoff in seconds (doubles each retry)",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional HTTP headers to send with webhook requests",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer this webhook belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type of event that triggered this delivery", max_length=50
                    ),
                ),
                (
                    "event_id",
                    models.IntegerField(help_text="ID of the entity that triggered the event"),
                ),
                ("payload", models.JSONField(help_text="JSON payload sent to the webhook URL")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(default=0, help_text="Number of delivery attempts"),
                ),
                (
                    "http_status",
                    models.IntegerField(
                        blank=True, help_text="HTTP status code from last attempt", null=True
                    ),
                ),
                (
                    "response_body",
                    models.TextField(
                        blank=True,
                        help_text="Response body from last attempt (truncated to 10KB)",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message from last failed attempt", null=True
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True, help_text="Request duration in milliseconds", null=True
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, help_text="Scheduled time for next retry attempt", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        help_text="Webhook configuration used for this delivery",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhook",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["customer"], name="webhooks_we_custome_a8ca10_idx"),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["enabled"], name="webhooks_we_enabled_49016f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="webhook",
            unique_together={("customer", "name")},
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["webhook"], name="webhooks_we_webhook_37bf82_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["status"], name="webhooks_we_status_6d768a_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["event_type"], name="webhooks_we_event_t_87580f_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["created_at"], name="webhooks_we_created_d5a8af_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["next_retry_at"], name="webhooks_we_next_re_8ddc98_idx"),
        ),
    ]
