# Generated by Django 5.2.8 on 2025-11-27 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "DEBUG"),
                            ("INFO", "INFO"),
                            ("WARN", "WARN"),
                            ("ERROR", "ERROR"),
                        ],
                        max_length=10,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField()),
                ("extra_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["ts"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("run_commands", "Run commands"),
                            ("config_backup", "Config backup"),
                            ("config_deploy_preview", "Config deploy preview"),
                            ("config_deploy_commit", "Config deploy commit"),
                            ("compliance_check", "Compliance check"),
                            ("topology_discovery", "Topology discovery"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("target_summary_json", models.JSONField(blank=True, null=True)),
                ("result_summary_json", models.JSONField(blank=True, null=True)),
                ("payload_json", models.JSONField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
