# Generated by Django 5.2.8 on 2025-11-27 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="joblog",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="jobs.job"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status"], name="jobs_job_status_7d017a_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["type"], name="jobs_job_type_b80e2d_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["user"], name="jobs_job_user_id_d7ccac_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["customer"], name="jobs_job_custome_6559db_idx"),
        ),
        migrations.AddIndex(
            model_name="joblog",
            index=models.Index(fields=["job"], name="jobs_joblog_job_id_3de730_idx"),
        ),
    ]
