# Generated by Django 5.2.8 on 2025-11-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="joblog",
            index=models.Index(fields=["job", "ts"], name="jobs_joblog_job_ts_idx"),
        ),
    ]
