# Generated by Django 5.2.8 on 2025-12-01 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_joblog_ts_index"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="joblog",
            new_name="jobs_joblog_job_id_047467_idx",
            old_name="jobs_joblog_job_ts_idx",
        ),
    ]
