# Generated by Django 5.2.8 on 2025-12-02 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_ssh_host_key_policy"),
        ("jobs", "0004_git_integration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("job_type", models.CharField(max_length=50)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "interval_type",
                    models.CharField(
                        choices=[
                            ("cron", "CRON Expression"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True, help_text="Cron expression (e.g., '0 2 * * *')", max_length=255
                    ),
                ),
                ("target_summary_json", models.JSONField(blank=True, null=True)),
                ("payload_json", models.JSONField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="jobs.schedule",
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["customer"], name="jobs_schedu_custome_ee0612_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["enabled"], name="jobs_schedu_enabled_f7bfba_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["next_run"], name="jobs_schedu_next_ru_5cba61_idx"),
        ),
    ]
