# Generated by Django 5.2.8 on 2025-12-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_git_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="custom_fields",
            field=models.JSONField(
                blank=True, default=dict, help_text="Custom field values stored as JSON"
            ),
        ),
    ]
