# Generated by Django 5.2.8 on 2025-12-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_git_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("run_commands", "Run commands"),
                    ("config_backup", "Config backup"),
                    ("config_deploy_preview", "Config deploy preview"),
                    ("config_deploy_commit", "Config deploy commit"),
                    ("compliance_check", "Compliance check"),
                    ("topology_discovery", "Topology discovery"),
                    ("ansible_playbook", "Ansible playbook"),
                ],
                max_length=50,
            ),
        ),
    ]
