# Generated by Django 5.2.8 on 2025-12-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_add_custom_fields"),
        ("jobs", "0005_add_region_to_job"),
        ("jobs", "0005_alter_job_type"),
        ("jobs", "0005_schedule_job_schedule_and_more"),
    ]

    operations = []
