# Generated by Django 5.2.8 on 2025-11-27 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("config_mgmt", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configsnapshot",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="config_snapshots",
                to="jobs.job",
            ),
        ),
        migrations.AddIndex(
            model_name="configsnapshot",
            index=models.Index(fields=["device"], name="config_mgmt_device__013372_idx"),
        ),
        migrations.AddIndex(
            model_name="configsnapshot",
            index=models.Index(fields=["created_at"], name="config_mgmt_created_86bc44_idx"),
        ),
    ]
