# Generated by Django 5.2.8 on 2025-12-01 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config_mgmt", "0002_initial"),
        ("customers", "0001_initial"),
        ("jobs", "0004_git_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="configsnapshot",
            name="git_commit_hash",
            field=models.CharField(
                blank=True,
                help_text="Git commit SHA this snapshot was synced in",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="configsnapshot",
            name="git_synced",
            field=models.BooleanField(
                default=False, help_text="Whether this snapshot has been synced to Git"
            ),
        ),
        migrations.CreateModel(
            name="GitRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this repository configuration", max_length=100
                    ),
                ),
                (
                    "remote_url",
                    models.CharField(
                        help_text="Git remote URL (HTTPS or SSH format)", max_length=500
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        default="main", help_text="Branch to push configs to", max_length=100
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("token", "Access Token (HTTPS)"), ("ssh_key", "SSH Key")],
                        default="token",
                        help_text="Authentication method",
                        max_length=20,
                    ),
                ),
                (
                    "_auth_token",
                    models.TextField(
                        blank=True,
                        db_column="auth_token",
                        help_text="Encrypted access token for HTTPS authentication",
                        null=True,
                    ),
                ),
                (
                    "_ssh_private_key",
                    models.TextField(
                        blank=True,
                        db_column="ssh_private_key",
                        help_text="Encrypted SSH private key for SSH authentication",
                        null=True,
                    ),
                ),
                (
                    "path_structure",
                    models.CharField(
                        choices=[
                            ("by_customer", "By Customer: /{customer}/{device}/config.txt"),
                            ("by_site", "By Site: /{site}/{device}/config.txt"),
                            ("flat", "Flat: /{device}.txt"),
                        ],
                        default="by_customer",
                        help_text="Directory structure for config files in the repository",
                        max_length=20,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Whether auto-push is enabled after backups"
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, help_text="Last successful sync timestamp", null=True
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        help_text="Status of last sync attempt",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "last_sync_message",
                    models.TextField(
                        blank=True, help_text="Message or error from last sync attempt", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        help_text="Customer this repository belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_repository",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Git Repository",
                "verbose_name_plural": "Git Repositories",
            },
        ),
        migrations.CreateModel(
            name="GitSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "commit_hash",
                    models.CharField(
                        blank=True,
                        help_text="Git commit SHA if sync was successful",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "files_synced",
                    models.IntegerField(
                        default=0, help_text="Number of config files pushed in this sync"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Commit message or error details", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated backup job that triggered this sync",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="git_sync_logs",
                        to="jobs.job",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="config_mgmt.gitrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="configsnapshot",
            name="git_sync_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="snapshots",
                to="config_mgmt.gitsynclog",
            ),
        ),
        migrations.AddIndex(
            model_name="gitsynclog",
            index=models.Index(fields=["repository"], name="config_mgmt_reposit_252d4a_idx"),
        ),
        migrations.AddIndex(
            model_name="gitsynclog",
            index=models.Index(fields=["status"], name="config_mgmt_status_552384_idx"),
        ),
        migrations.AddIndex(
            model_name="gitsynclog",
            index=models.Index(fields=["started_at"], name="config_mgmt_started_ec2e8c_idx"),
        ),
    ]
