# Generated by Django 5.2.8 on 2025-12-01 20:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config_mgmt", "0003_git_integration"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Template description and usage notes", null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("base", "Base Config (hostname, logging, NTP)"),
                            ("interface", "Interface Templates"),
                            ("routing", "Routing Protocols"),
                            ("security", "Security Policies"),
                            ("custom", "Custom Templates"),
                        ],
                        default="custom",
                        help_text="Template category for organization",
                        max_length=20,
                    ),
                ),
                ("template_content", models.TextField(help_text="Jinja2 template content")),
                (
                    "variables_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Variable definitions: {name: {type, required, default, description, validation}}",
                    ),
                ),
                (
                    "platform_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of compatible platform/vendor tags (e.g., ['cisco_ios', 'juniper'])",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is available for use"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer this template belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_templates",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(fields=["customer"], name="config_mgmt_custome_ff737c_idx"),
                    models.Index(fields=["category"], name="config_mgmt_categor_e43150_idx"),
                    models.Index(fields=["is_active"], name="config_mgmt_is_acti_1aa2ca_idx"),
                ],
                "unique_together": {("customer", "name")},
            },
        ),
    ]
