# Generated by Django 5.2.8 on 2025-12-01 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_mgmt', '0004_config_templates'),
        ('devices', '0006_add_drift_analysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('additions', models.IntegerField(default=0, help_text='Number of lines added')),
                ('deletions', models.IntegerField(default=0, help_text='Number of lines deleted')),
                ('changes', models.IntegerField(default=0, help_text='Number of lines changed')),
                ('total_lines', models.IntegerField(default=0, help_text='Total lines in diff output')),
                ('has_changes', models.BooleanField(default=False, help_text='Whether any changes were detected')),
                ('diff_summary', models.TextField(blank=True, help_text='Summary of major changes')),
                ('device', models.ForeignKey(help_text='Device this drift analysis belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='config_drifts', to='devices.device')),
                ('snapshot_from', models.ForeignKey(help_text='Earlier snapshot in comparison', on_delete=django.db.models.deletion.CASCADE, related_name='drifts_as_from', to='config_mgmt.configsnapshot')),
                ('snapshot_to', models.ForeignKey(help_text='Later snapshot in comparison', on_delete=django.db.models.deletion.CASCADE, related_name='drifts_as_to', to='config_mgmt.configsnapshot')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered the backup that created this drift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_drifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DriftAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', help_text='Alert severity level', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', help_text='Alert status', max_length=20)),
                ('message', models.TextField(help_text='Alert message describing the change')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about alert resolution')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_drift_alerts', to=settings.AUTH_USER_MODEL)),
                ('drift', models.ForeignKey(help_text='Associated drift analysis', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='config_mgmt.configdrift')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='configdrift',
            index=models.Index(fields=['device'], name='config_mgmt_device__c087c6_idx'),
        ),
        migrations.AddIndex(
            model_name='configdrift',
            index=models.Index(fields=['detected_at'], name='config_mgmt_detecte_d2c42d_idx'),
        ),
        migrations.AddIndex(
            model_name='configdrift',
            index=models.Index(fields=['has_changes'], name='config_mgmt_has_cha_d907b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configdrift',
            unique_together={('snapshot_from', 'snapshot_to')},
        ),
        migrations.AddIndex(
            model_name='driftalert',
            index=models.Index(fields=['severity'], name='config_mgmt_severit_47ffa5_idx'),
        ),
        migrations.AddIndex(
            model_name='driftalert',
            index=models.Index(fields=['status'], name='config_mgmt_status_8b4ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='driftalert',
            index=models.Index(fields=['detected_at'], name='config_mgmt_detecte_3460a0_idx'),
        ),
    ]
