# Generated by Django 5.2.8 on 2025-12-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_mgmt", "0005_add_drift_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="configsnapshot",
            name="custom_fields",
            field=models.JSONField(
                blank=True, default=dict, help_text="Custom field values stored as JSON"
            ),
        ),
        migrations.AddField(
            model_name="configtemplate",
            name="custom_fields",
            field=models.JSONField(
                blank=True, default=dict, help_text="Custom field values stored as JSON"
            ),
        ),
    ]
