# Generated by Django 5.2.8 on 2025-12-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smtpconfig",
            name="password",
        ),
        migrations.AddField(
            model_name="smtpconfig",
            name="_password",
            field=models.TextField(
                blank=True, db_column="password", help_text="Encrypted SMTP password", null=True
            ),
        ),
    ]
