# Generated by Django 5.2.8 on 2025-12-02 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_customer_ssh_host_key_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name (used in API, must be unique per model)",
                        max_length=100,
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Display label for the field", max_length=100),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("device", "Device"),
                            ("credential", "Credential"),
                            ("job", "Job"),
                            ("compliancepolicy", "Compliance Policy"),
                            ("configsnapshot", "Config Snapshot"),
                            ("configtemplate", "Config Template"),
                            ("tag", "Tag"),
                            ("devicegroup", "Device Group"),
                        ],
                        help_text="Which model this field applies to",
                        max_length=50,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text (Single Line)"),
                            ("textarea", "Text (Multi-Line)"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("url", "URL"),
                            ("json", "JSON"),
                            ("select", "Selection (Dropdown)"),
                            ("multiselect", "Multi-Select"),
                        ],
                        default="text",
                        help_text="Data type for this field",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description or help text for this field", null=True
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, help_text="Whether this field is required"),
                ),
                (
                    "default_value",
                    models.TextField(
                        blank=True,
                        help_text="Default value (as string, will be converted to field type)",
                        null=True,
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        help_text="For select/multiselect: list of valid choices",
                        null=True,
                    ),
                ),
                (
                    "validation_regex",
                    models.CharField(
                        blank=True,
                        help_text="Optional regex pattern for text validation",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "validation_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Minimum value for integer/decimal fields",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "validation_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Maximum value for integer/decimal fields",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=100, help_text="Display order (lower numbers appear first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this field is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer this custom field belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_definitions",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["model_type", "weight", "name"],
                "indexes": [
                    models.Index(fields=["customer"], name="core_custom_custome_6c5e92_idx"),
                    models.Index(fields=["model_type"], name="core_custom_model_t_c7fa20_idx"),
                    models.Index(fields=["is_active"], name="core_custom_is_acti_3ea261_idx"),
                ],
                "unique_together": {("customer", "model_type", "name")},
            },
        ),
    ]
