# Generated by Django 5.2.8 on 2025-12-02 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_ssh_host_key_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name for the region (e.g., 'US East', 'Europe West')", max_length=100)),
                ('identifier', models.SlugField(help_text="Unique identifier for routing (e.g., 'us-east-1', 'eu-west-1')")),
                ('api_endpoint', models.URLField(blank=True, help_text='Optional API endpoint URL for this region (for distributed API)', max_length=500, null=True)),
                ('worker_pool_config', models.JSONField(blank=True, default=dict, help_text='Configuration for Celery worker pool (concurrency, queues, etc.)')),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('offline', 'Offline')], default='healthy', help_text='Current health status of the region', max_length=20)),
                ('last_health_check', models.DateTimeField(blank=True, help_text='Timestamp of last health check', null=True)),
                ('health_check_interval_seconds', models.IntegerField(default=60, help_text='Interval in seconds between health checks')),
                ('priority', models.IntegerField(default=100, help_text='Priority for job routing (higher = preferred). Used for failover.')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this region is enabled for job routing')),
                ('description', models.TextField(blank=True, help_text='Optional description of the region', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer this region belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='customers.customer')),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['customer'], name='core_region_custome_c5e5ea_idx'), models.Index(fields=['identifier'], name='core_region_identif_b0598b_idx'), models.Index(fields=['health_status'], name='core_region_health__2045bc_idx'), models.Index(fields=['enabled'], name='core_region_enabled_a94eff_idx')],
                'unique_together': {('customer', 'identifier')},
            },
        ),
    ]
