# Generated by Django 5.2.8 on 2025-12-02 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_customer_ssh_host_key_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnsibleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ansible_cfg_content",
                    models.TextField(
                        blank=True, default="", help_text="Custom ansible.cfg content (optional)"
                    ),
                ),
                (
                    "vault_password",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted vault password for Ansible Vault",
                    ),
                ),
                (
                    "collections",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Ansible collections to install (e.g., ['cisco.ios', 'ansible.netcommon'])",
                    ),
                ),
                (
                    "environment_vars",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Environment variables for Ansible execution",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        help_text="Customer this Ansible configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ansible_config",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ansible Configuration",
                "verbose_name_plural": "Ansible Configurations",
            },
        ),
        migrations.CreateModel(
            name="Playbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Playbook name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Playbook description"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("inline", "Inline Content"),
                            ("git", "Git Repository"),
                            ("upload", "File Upload"),
                        ],
                        default="inline",
                        help_text="Source type of the playbook",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", help_text="Inline playbook content (YAML)"
                    ),
                ),
                (
                    "git_repo_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Git repository URL (for git source)",
                        max_length=500,
                    ),
                ),
                (
                    "git_branch",
                    models.CharField(
                        blank=True, default="main", help_text="Git branch name", max_length=100
                    ),
                ),
                (
                    "git_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path to playbook within git repository",
                        max_length=500,
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default variables for playbook execution",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for categorizing playbooks"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Whether this playbook is enabled for execution"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this playbook",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_playbooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer this playbook belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbooks",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["customer"], name="ansible_mgm_custome_6d6e4c_idx"),
                    models.Index(fields=["name"], name="ansible_mgm_name_5f1c27_idx"),
                    models.Index(fields=["enabled"], name="ansible_mgm_enabled_756aa2_idx"),
                ],
                "unique_together": {("customer", "name")},
            },
        ),
    ]
