# Generated by Django 5.2.8 on 2025-12-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ansible_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbook",
            name="uploaded_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded playbook file (for upload source)",
                null=True,
                upload_to="playbooks/%Y/%m/",
            ),
        ),
    ]
