# Generated by Django 5.2.8 on 2025-11-27 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliance", "0001_initial"),
        ("customers", "0001_initial"),
        ("devices", "0001_initial"),
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancepolicy",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compliancepolicy",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_policies",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="complianceresult",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_results",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="complianceresult",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_results",
                to="jobs.job",
            ),
        ),
        migrations.AddField(
            model_name="complianceresult",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="compliance.compliancepolicy",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="compliancepolicy",
            unique_together={("customer", "name")},
        ),
        migrations.AddIndex(
            model_name="complianceresult",
            index=models.Index(fields=["policy"], name="compliance__policy__240522_idx"),
        ),
        migrations.AddIndex(
            model_name="complianceresult",
            index=models.Index(fields=["device"], name="compliance__device__193d99_idx"),
        ),
        migrations.AddIndex(
            model_name="complianceresult",
            index=models.Index(fields=["ts"], name="compliance__ts_99fb95_idx"),
        ),
    ]
