# Generated by Django 5.2.8 on 2025-12-01 22:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_initial"),
        ("config_mgmt", "0004_config_templates"),
        ("devices", "0006_alter_netboxconfig__api_token"),
        ("jobs", "0004_git_integration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RemediationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "config_snippet",
                    models.TextField(help_text="Configuration commands to apply as remediation"),
                ),
                (
                    "approval_required",
                    models.CharField(
                        choices=[
                            ("none", "No Approval Required"),
                            ("manual", "Manual Approval Required"),
                            ("auto", "Auto-approve for Non-critical"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "max_daily_executions",
                    models.IntegerField(
                        default=10,
                        help_text="Maximum number of remediations per day to prevent runaway fixes",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "apply_mode",
                    models.CharField(
                        choices=[("merge", "Merge"), ("replace", "Replace")],
                        default="merge",
                        help_text="How to apply the configuration",
                        max_length=20,
                    ),
                ),
                (
                    "verify_after",
                    models.BooleanField(
                        default=True, help_text="Re-run compliance check after applying remediation"
                    ),
                ),
                (
                    "rollback_on_failure",
                    models.BooleanField(
                        default=True, help_text="Rollback changes if verification fails"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remediation_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remediation_rules",
                        to="compliance.compliancepolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["policy", "name"],
            },
        ),
        migrations.CreateModel(
            name="RemediationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "verification_passed",
                    models.BooleanField(
                        blank=True,
                        help_text="Did the compliance check pass after remediation",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "after_snapshot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Configuration snapshot after remediation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remediation_after",
                        to="config_mgmt.configsnapshot",
                    ),
                ),
                (
                    "before_snapshot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Configuration snapshot before remediation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remediation_before",
                        to="config_mgmt.configsnapshot",
                    ),
                ),
                (
                    "compliance_result",
                    models.ForeignKey(
                        help_text="The compliance violation that triggered this remediation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remediation_actions",
                        to="compliance.complianceresult",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remediation_actions",
                        to="devices.device",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remediation_actions",
                        to="jobs.job",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="compliance.remediationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="remediationrule",
            index=models.Index(fields=["policy"], name="compliance__policy__d9f2dc_idx"),
        ),
        migrations.AddIndex(
            model_name="remediationrule",
            index=models.Index(fields=["enabled"], name="compliance__enabled_b5e976_idx"),
        ),
        migrations.AddIndex(
            model_name="remediationaction",
            index=models.Index(fields=["rule"], name="compliance__rule_id_82d465_idx"),
        ),
        migrations.AddIndex(
            model_name="remediationaction",
            index=models.Index(fields=["device"], name="compliance__device__8eea49_idx"),
        ),
        migrations.AddIndex(
            model_name="remediationaction",
            index=models.Index(fields=["status"], name="compliance__status_4687ec_idx"),
        ),
        migrations.AddIndex(
            model_name="remediationaction",
            index=models.Index(fields=["started_at"], name="compliance__started_ae7d94_idx"),
        ),
    ]
