# Generated by Django 5.2.8 on 2025-12-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0003_remediationrule_remediationaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remediationrule",
            name="rollback_on_failure",
            field=models.BooleanField(
                default=True, help_text="Rollback changes if remediation fails"
            ),
        ),
    ]
