# Generated by Django 5.2.8 on 2025-12-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0003_remediationrule_remediationaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancepolicy",
            name="custom_fields",
            field=models.JSONField(
                blank=True, default=dict, help_text="Custom field values stored as JSON"
            ),
        ),
        migrations.AlterField(
            model_name="remediationrule",
            name="rollback_on_failure",
            field=models.BooleanField(
                default=True, help_text="Rollback changes if remediation fails"
            ),
        ),
    ]
