# Generated by Django 5.2.8 on 2025-12-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0004_add_custom_fields"),
        ("compliance", "0004_alter_remediationrule_rollback_on_failure"),
    ]

    operations = []
